### ISSUE TITLE
Delete this repo ?

### ISSUE THREAD

**Issue by fchapoton** [sagemath/cloud.sagemath.org#1]
Given that this is fully obsolete, may we delete this repo now ?

**Comment by haraldschilly** [comment]
well, the redirect is handled by cloudflare now. we could keep it as a fallback, in case sagemath.org is ever managed by something else than cloudflare? besides that, it's worth to fix the actual URL :grin:

**Comment by haraldschilly** [comment]
url is fixed, and that wrong URL still appears on websites in the wild. so, I'm for keeping it.

**Comment by fchapoton** [comment]
ok, then close the issue
